// ===----------------------------------------------------------------------===//
//
// This source file is part of the swift-linter-rules open source project
//
// Copyright (c) 2026 Coen ten Thije Boonkkamp and the swift-linter-rules project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
//
// ===----------------------------------------------------------------------===//
//
// !!! AUTO-GENERATED — DO NOT EDIT !!!
//
// This file is regenerated by
// `swift-linter-rules/Scripts/regenerate-stdlib-refinements.sh`.
// The generator is the `symbol-graph-conformance-oracle` experiment
// at `swift-foundations/swift-json/Experiments/`.
//
// Source: `Swift` module's symbol graph emitted by
// `Apple Swift version 6.3.2 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)`.
// Run date: 2026-05-13
// Pair count: 136
//
// To regenerate against a newer toolchain, run the script. To audit the
// generation pipeline, see the experiment's main.swift header for the
// exact `swift symbolgraph-extract` recipe.

/// Stdlib protocol refinements: each pair `(refining, refined)` means
/// `refining` declares `: refined` in the standard library (directly or
/// transitively), so a composition `refining & refined` (in either order)
/// is redundant.
///
/// Sourced from the transitive closure of protocol→protocol
/// `conformsTo` relationships in the Swift module's symbol graph.
@usableFromInline
internal let idiomKnownStdlibRefinements: [(refining: Swift.String, refined: Swift.String)] = [
    ("AdditiveArithmetic", "Equatable"),
    ("BidirectionalCollection", "Collection"),
    ("BidirectionalCollection", "Sequence"),
    ("BinaryFloatingPoint", "AdditiveArithmetic"),
    ("BinaryFloatingPoint", "Comparable"),
    ("BinaryFloatingPoint", "Equatable"),
    ("BinaryFloatingPoint", "ExpressibleByFloatLiteral"),
    ("BinaryFloatingPoint", "ExpressibleByIntegerLiteral"),
    ("BinaryFloatingPoint", "FloatingPoint"),
    ("BinaryFloatingPoint", "Hashable"),
    ("BinaryFloatingPoint", "Numeric"),
    ("BinaryFloatingPoint", "SignedNumeric"),
    ("BinaryFloatingPoint", "Strideable"),
    ("BinaryInteger", "AdditiveArithmetic"),
    ("BinaryInteger", "Comparable"),
    ("BinaryInteger", "CustomStringConvertible"),
    ("BinaryInteger", "Equatable"),
    ("BinaryInteger", "ExpressibleByIntegerLiteral"),
    ("BinaryInteger", "Hashable"),
    ("BinaryInteger", "Numeric"),
    ("BinaryInteger", "Strideable"),
    ("CodingKey", "CustomDebugStringConvertible"),
    ("CodingKey", "CustomStringConvertible"),
    ("CodingKey", "Sendable"),
    ("CodingKey", "SendableMetatype"),
    ("Collection", "Sequence"),
    ("Comparable", "Equatable"),
    ("CustomLeafReflectable", "CustomReflectable"),
    ("DurationProtocol", "AdditiveArithmetic"),
    ("DurationProtocol", "Comparable"),
    ("DurationProtocol", "Equatable"),
    ("DurationProtocol", "Sendable"),
    ("DurationProtocol", "SendableMetatype"),
    ("Error", "Sendable"),
    ("Error", "SendableMetatype"),
    ("ExpressibleByExtendedGraphemeClusterLiteral", "ExpressibleByUnicodeScalarLiteral"),
    ("ExpressibleByStringInterpolation", "ExpressibleByExtendedGraphemeClusterLiteral"),
    ("ExpressibleByStringInterpolation", "ExpressibleByStringLiteral"),
    ("ExpressibleByStringInterpolation", "ExpressibleByUnicodeScalarLiteral"),
    ("ExpressibleByStringLiteral", "ExpressibleByExtendedGraphemeClusterLiteral"),
    ("ExpressibleByStringLiteral", "ExpressibleByUnicodeScalarLiteral"),
    ("FixedWidthInteger", "AdditiveArithmetic"),
    ("FixedWidthInteger", "BinaryInteger"),
    ("FixedWidthInteger", "Comparable"),
    ("FixedWidthInteger", "CustomStringConvertible"),
    ("FixedWidthInteger", "Equatable"),
    ("FixedWidthInteger", "ExpressibleByIntegerLiteral"),
    ("FixedWidthInteger", "Hashable"),
    ("FixedWidthInteger", "LosslessStringConvertible"),
    ("FixedWidthInteger", "Numeric"),
    ("FixedWidthInteger", "Strideable"),
    ("FloatingPoint", "AdditiveArithmetic"),
    ("FloatingPoint", "Comparable"),
    ("FloatingPoint", "Equatable"),
    ("FloatingPoint", "ExpressibleByIntegerLiteral"),
    ("FloatingPoint", "Hashable"),
    ("FloatingPoint", "Numeric"),
    ("FloatingPoint", "SignedNumeric"),
    ("FloatingPoint", "Strideable"),
    ("Hashable", "Equatable"),
    ("InstantProtocol", "Comparable"),
    ("InstantProtocol", "Equatable"),
    ("InstantProtocol", "Hashable"),
    ("InstantProtocol", "Sendable"),
    ("InstantProtocol", "SendableMetatype"),
    ("LazyCollectionProtocol", "Collection"),
    ("LazyCollectionProtocol", "LazySequenceProtocol"),
    ("LazyCollectionProtocol", "Sequence"),
    ("LazySequenceProtocol", "Sequence"),
    ("LosslessStringConvertible", "CustomStringConvertible"),
    ("MutableCollection", "Collection"),
    ("MutableCollection", "Sequence"),
    ("Numeric", "AdditiveArithmetic"),
    ("Numeric", "Equatable"),
    ("Numeric", "ExpressibleByIntegerLiteral"),
    ("OptionSet", "Equatable"),
    ("OptionSet", "ExpressibleByArrayLiteral"),
    ("OptionSet", "RawRepresentable"),
    ("OptionSet", "SetAlgebra"),
    ("RandomAccessCollection", "BidirectionalCollection"),
    ("RandomAccessCollection", "Collection"),
    ("RandomAccessCollection", "Sequence"),
    ("RangeReplaceableCollection", "Collection"),
    ("RangeReplaceableCollection", "Sequence"),
    ("SIMD", "CustomStringConvertible"),
    ("SIMD", "Decodable"),
    ("SIMD", "Encodable"),
    ("SIMD", "Equatable"),
    ("SIMD", "ExpressibleByArrayLiteral"),
    ("SIMD", "Hashable"),
    ("SIMD", "SIMDStorage"),
    ("SIMDScalar", "BitwiseCopyable"),
    ("Sendable", "SendableMetatype"),
    ("SetAlgebra", "Equatable"),
    ("SetAlgebra", "ExpressibleByArrayLiteral"),
    ("SignedInteger", "AdditiveArithmetic"),
    ("SignedInteger", "BinaryInteger"),
    ("SignedInteger", "Comparable"),
    ("SignedInteger", "CustomStringConvertible"),
    ("SignedInteger", "Equatable"),
    ("SignedInteger", "ExpressibleByIntegerLiteral"),
    ("SignedInteger", "Hashable"),
    ("SignedInteger", "Numeric"),
    ("SignedInteger", "SignedNumeric"),
    ("SignedInteger", "Strideable"),
    ("SignedNumeric", "AdditiveArithmetic"),
    ("SignedNumeric", "Equatable"),
    ("SignedNumeric", "ExpressibleByIntegerLiteral"),
    ("SignedNumeric", "Numeric"),
    ("Strideable", "Comparable"),
    ("Strideable", "Equatable"),
    ("StringProtocol", "BidirectionalCollection"),
    ("StringProtocol", "Collection"),
    ("StringProtocol", "Comparable"),
    ("StringProtocol", "CustomStringConvertible"),
    ("StringProtocol", "Equatable"),
    ("StringProtocol", "ExpressibleByExtendedGraphemeClusterLiteral"),
    ("StringProtocol", "ExpressibleByStringInterpolation"),
    ("StringProtocol", "ExpressibleByStringLiteral"),
    ("StringProtocol", "ExpressibleByUnicodeScalarLiteral"),
    ("StringProtocol", "Hashable"),
    ("StringProtocol", "LosslessStringConvertible"),
    ("StringProtocol", "Sequence"),
    ("StringProtocol", "TextOutputStream"),
    ("StringProtocol", "TextOutputStreamable"),
    ("UnsafeSendable", "Sendable"),
    ("UnsafeSendable", "SendableMetatype"),
    ("UnsignedInteger", "AdditiveArithmetic"),
    ("UnsignedInteger", "BinaryInteger"),
    ("UnsignedInteger", "Comparable"),
    ("UnsignedInteger", "CustomStringConvertible"),
    ("UnsignedInteger", "Equatable"),
    ("UnsignedInteger", "ExpressibleByIntegerLiteral"),
    ("UnsignedInteger", "Hashable"),
    ("UnsignedInteger", "Numeric"),
    ("UnsignedInteger", "Strideable"),
]
