// ===----------------------------------------------------------------------===//
//
// This source file is part of the swift-linter-rules open source project
//
// Copyright (c) 2026 Coen ten Thije Boonkkamp and the swift-linter-rules project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
//
// ===----------------------------------------------------------------------===//

public import Linter_Primitives
internal import SwiftSyntax

/// Flags `A & B` compositions where `A` already refines `B` in the
/// standard library. The `& B` half is redundant — the compiler enforces
/// `B` through `A`'s refinement chain.
///
/// The rule consults `idiomKnownStdlibRefinements`, an auto-generated
/// table in a sibling file. The table is produced by the
/// `symbol-graph-conformance-oracle` experiment at
/// `swift-foundations/swift-json/Experiments/` and regenerated by
/// `Scripts/regenerate-stdlib-refinements.sh` in this package. The rule
/// itself remains AST-only — the table is a precomputed snapshot of
/// stdlib's protocol-refinement graph, not a live type-resolution
/// backend (per `swift-foundations/swift-linter/Research/lsp-sourcekit-integration.md`
/// v1.2.0).
extension Lint.Rule {
    public static let `redundant refinement` = Lint.Rule(
        id: "redundant refinement",
        default: .warning,
        findings: { source, severity in
            let visitor = IdiomRedundantRefinementVisitor(
                source: source.file,
                severity: severity,
                converter: source.converter
            )
            visitor.walk(source.tree)
            return visitor.matches
        }
    )
}

@usableFromInline
internal func idiomRedundantRefinementMessage(
    refining: Swift.String,
    refined: Swift.String
) -> Swift.String {
    "[redundant refinement] feedback_redundant_protocol_refinement: "
        + "`\(refining) & \(refined)` — `\(refining)` already refines `\(refined)` "
        + "in the standard library. The `& \(refined)` half is redundant; "
        + "the compiler enforces `\(refined)` through `\(refining)`. Drop "
        + "the redundant member."
}

internal final class IdiomRedundantRefinementVisitor: SyntaxVisitor {
    let source: Source.File
    let severity: Diagnostic.Severity
    let converter: SourceLocationConverter
    var matches: [Diagnostic.Record] = []

    init(source: Source.File, severity: Diagnostic.Severity, converter: SourceLocationConverter) {
        self.source = source
        self.severity = severity
        self.converter = converter
        super.init(viewMode: .sourceAccurate)
    }

    override func visit(_ node: CompositionTypeSyntax) -> SyntaxVisitorContinueKind {
        // Collect the leaf identifier of each element + its position. Skip
        // elements with no leaf name (suppressed types like ~Copyable,
        // anonymous structural types, etc.).
        var leaves: [(name: Swift.String, position: AbsolutePosition)] = []
        for element in node.elements {
            if let name = leafName(of: element.type) {
                leaves.append((name, element.type.positionAfterSkippingLeadingTrivia))
            }
        }
        // For each ordered pair (i, j), check whether leaves[i] refines
        // leaves[j]. Report at the position of the redundant (refined)
        // leaf — that's the member to delete.
        var reportedPositions: Swift.Set<AbsolutePosition> = []
        for i in 0..<leaves.count {
            for j in 0..<leaves.count where i != j {
                let refining = leaves[i].name
                let refined = leaves[j].name
                let isRedundant = idiomKnownStdlibRefinements.contains { pair in
                    pair.refining == refining && pair.refined == refined
                }
                guard isRedundant else { continue }
                let position = leaves[j].position
                guard !reportedPositions.contains(position) else { continue }
                reportedPositions.insert(position)
                let location = converter.location(for: position)
                matches.append(
                    Diagnostic.Record(
                        location: Source.Location(
                            fileID: source.fileID,
                            filePath: source.filePath,
                            line: location.line,
                            column: location.column
                        ),
                        severity: severity,
                        identifier: "redundant refinement",
                        message: idiomRedundantRefinementMessage(
                            refining: refining,
                            refined: refined
                        )
                    )
                )
            }
        }
        return .visitChildren
    }

    /// Returns the rightmost identifier of a type expression — e.g.
    /// `Swift.Error` → `Error`, `Error` → `Error`. Existential `any P`
    /// and `some P` unwrap to their constraint. Suppression types
    /// (`~Copyable`) and structural types return nil so they cannot
    /// shadow a real refinement-table entry.
    private func leafName(of type: TypeSyntax) -> Swift.String? {
        if let identifier = type.as(IdentifierTypeSyntax.self) {
            return identifier.name.text
        }
        if let member = type.as(MemberTypeSyntax.self) {
            return member.name.text
        }
        if let some = type.as(SomeOrAnyTypeSyntax.self) {
            return leafName(of: some.constraint)
        }
        return nil
    }
}
